version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - export COMPOSER_ROOT_VERSION=2.2.6
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer --version

  pre_build:
    commands:
      - export COMPOSER_ROOT_VERSION=2.2.6
      - echo Building the application...
      - composer install --no-dev --optimize-autoloader -vvv

  build:
    commands:
      - export COMPOSER_ROOT_VERSION=2.2.6
      - tail -f /var/log/eb-engine.log &
