version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer | bash
      - export PATH="$HOME/.phpenv/bin:$PATH"
      - eval "$(phpenv init -)"
      - phpenv install 8.2.0
      - phpenv global 8.2.0
      - php -v
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-dev --optimize-autoloader -vvv

  build:
    commands:
        # Verifica los logs en tiempo real durante la instalación
      - tail -f /var/log/eb-activity.log &  # Para ver los logs de actividad de Elastic Beanstalk en tiempo real
      - composer install --no-dev --optimize-autoloader -vvv
artifacts:
  files:
    - '**/*'
  discard-paths: yes