version: 0.3

phases:
  install:
    commands:
      - curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer | bash
      - export PATH="$HOME/.phpenv/bin:$PATH"
      - eval "$(phpenv init -)"
      - phpenv install 8.0.1
      - phpenv global 8.0.1
      - php -v
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install

  build:
    commands:
      - cp .env.example .env
      - php artisan key:generate
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

artifacts:
  files:
    - '**/*'
  discard-paths: yes
