version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2 
    commands:
      - curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer | bash
      - export PATH="$HOME/.phpenv/bin:$PATH"
      - eval "$(phpenv init -)"
      - phpenv install 8.2.0
      - phpenv global 8.2.0
      - php -v
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install

  build:
    commands:
      - php artisan key:generate
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

artifacts:
  files:
    - '**/*'
  discard-paths: yes